# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.
"https://{default}/":
    type: upstream
    upstream: "admin-fe:http"
"https://settings.{default}/":
  type: upstream
  upstream: "settings-fe:http"
"https://api.{default}/":
    type: upstream
    upstream: "api-gateway:http"
"https://keycloack.{default}/":
    type: upstream
    upstream: "user-management-service:http"
"https://vault.{default}/":
  type: upstream
  upstream: "vault:http"
